name: Deploy Data Vue

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VUE_APP_CACHE_API_URL: https://cache.samifying.com/api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 22 LTS
        uses: actions/setup-node@v3
        with:
          node-version: '22.22.1'
          cache: 'npm'

      - run: npm install
      - run: npm run build

      - name: Setup 404 Routing
        run: cd dist && cp index.html 404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist